all:
  children:
    dev_hosts:
      hosts:
        docker-dev-01:
          ansible_host: 192.168.1.244
        docker-dev-02:
          ansible_host: 192.168.1.245
        docker-dev-03:
          ansible_host: 192.168.1.246
    test_hosts:
      hosts:
        docker-test-01:
          ansible_host: 192.168.1.251
        docker-test-02:
          ansible_host: 192.168.1.252
        docker-test-03:
          ansible_host: 192.168.1.253
  vars:
    ansible_user: dtaylor
    ansible_ssh_pass: "{{ vault_ssh_password }}"
    ansible_become_pass: "{{ vault_sudo_password }}"
    ansible_python_interpreter: /usr/bin/python3
