---
- name: Install K3s on Dev Cluster
  hosts: k3s_dev
  become: yes
  vars:
    k3s_version: "v1.29.0+k3s1"
    k3s_master_ip: "{{ hostvars['docker-dev-01']['ansible_host'] }}"
    
  tasks:
    - name: Install K3s on first master
      when: inventory_hostname == "docker-dev-01"
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        sh -s - server \
          --cluster-init \
          --disable traefik \
          --flannel-iface=ens19 \
          --node-ip={{ ansible_host }} \
          --cluster-cidr=10.42.0.0/16 \
          --service-cidr=10.43.0.0/16 \
          --write-kubeconfig-mode=644 \
          --node-label="node-role.kubernetes.io/master=true"
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      when: inventory_hostname == "docker-dev-01"
      wait_for:
        port: 6443
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 300

    - name: Get node token
      when: inventory_hostname == "docker-dev-01"
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Store token fact
      when: inventory_hostname == "docker-dev-01"
      set_fact:
        k3s_token: "{{ node_token.content | b64decode | trim }}"

    - name: Install K3s on workers
      when: 
        - inventory_hostname != "docker-dev-01"
        - k3s_role == "worker"
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_VERSION="{{ k3s_version }}" \
        K3S_URL="https://{{ k3s_master_ip }}:6443" \
        K3S_TOKEN="{{ hostvars['docker-dev-01']['k3s_token'] }}" \
        sh -s - \
          --flannel-iface=ens19 \
          --node-ip={{ ansible_host }}
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for all nodes to be ready
      when: inventory_hostname == "docker-dev-01"
      shell: kubectl get nodes --no-headers | wc -l
      register: node_count
      until: node_count.stdout | int == 3
      retries: 30
      delay: 10
      changed_when: false

    - name: Label worker nodes
      when: inventory_hostname == "docker-dev-01"
      shell: |
        kubectl label node docker-dev-02 node-role.kubernetes.io/worker=true --overwrite
        kubectl label node docker-dev-03 node-role.kubernetes.io/worker=true --overwrite
      changed_when: false
